version: '3.8'
services:
  frontend:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - backend
  backend:
    build: ./server
    ports:
      - "5000:5000"
    env_file: .env
    depends_on:
      - db
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: rehearsal
      POSTGRES_USER: rehearsal
      POSTGRES_PASSWORD: secret
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data: